[tool.poetry]
name = "eralchemy2"
version = "1.3.7"
description = "Simple entity relation (ER) diagrams generation"
authors = ["Florian Maurer <fmaurer@disroot.org>"]
license = "Apache License 2.0"
readme = "README.md"

homepage = "https://github.com/maurerle/eralchemy2"
repository = "https://github.com/maurerle/eralchemy2"

keywords = ["sql", "ORM", "relational databases", "ER diagram", "render"]

classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Database",
]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = ">=1.4"
pygraphviz = {version = "^1.7,!=1.8", optional = true}
flask-sqlalchemy = {version = ">=2.5.1", optional = true}
psycopg2 = {version = "^2.9.3", optional = true}
importlib_metadata = { version = ">=4.0.0", markers = "python_version < '3.8'" }

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
tox = "^4.4.6"
isort = "^5.10.1"
towncrier = "^22.8.0"
mypy  = "^0.971"

[tool.poetry.extras]
    ci = ["flask-sqlalchemy", "psycopg2"]
    pygraphviz = ["pygraphviz"]

[tool.poetry.scripts]
eralchemy2 = "eralchemy2.main:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.flake8]
max-line-length = 120

[tool.isort]
profile = "black"
add_imports = ["from __future__ import annotations"]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py37, py38, py39, py310, py310-SA14, py310-SA20, py311, py311-SA14, py311-SA20

[tox:.package]
# note tox will use the same python version as under what tox is installed to package
# so unless this is python 3 you can require a given python version for the packaging
# environment via the basepython key
basepython = python3

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310, py310-SA14, py310-SA20
    3.11: py311, py311-SA14, py311-SA20

[testenv]
extras = ci
deps =
  pytest
  py310-SA14: sqlalchemy~=1.4
  py311-SA14: sqlalchemy~=1.4
  py310-SA20: sqlalchemy~=2.0.4
  py311-SA20: sqlalchemy~=2.0.4
commands =
  pytest
"""

[tool.pytest]
testpaths = "tests"

[tool.towncrier]
name = "eralchemy2"
package = "eralchemy2"
directory = "changes"
filename = "NEWS.rst"

[tool.mypy]
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
# output
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true

[[tool.mypy.overrides]]
module = ["pygraphviz.*", "sqlalchemy.*"]
ignore_missing_imports = true
